on: [push]

jobs:
  test-different-versions:
    runs-on: ubuntu-latest
    name: It reads current and next versions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up git config
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
      - run: touch CHANGELOG.md
      - name: Create a simple changelog file
        uses: cucumber/action-changelog@v1.3
        with:
          args: init --output CHANGELOG.md --compare-url https://example.com/abcdef...HEAD
      - name: Create an initial commit
        run: |
          git commit -am "Add a changelog"
          git tag v0.0.0
      - name: Run changelog release
        uses: cucumber/action-changelog@v1.3
        with:
          args: release --output CHANGELOG.md 1.0.0
      - name: Commit release
        run: |
          git commit -am "Release v1.0.0"
      - name: Test the action
        uses: ./
        id: versions
      - name: Assert values
        run: |
          [ "${{ steps.versions.outputs.released-version }}" == "0.0.0" ]
          [ "${{ steps.versions.outputs.changelog-latest-version }}" == "1.0.0" ]
          [ "${{ steps.versions.outputs.is-release-required }}" == "true" ]

  test-same-version:
    runs-on: ubuntu-latest
    name: is-release-required should be false when versions are the same
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up git config
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
      - run: touch CHANGELOG.md
      - name: Create a simple changelog file
        uses: cucumber/action-changelog@v1.3
        with:
          args: init --output CHANGELOG.md --compare-url https://example.com/abcdef...HEAD
      - name: Create an initial commit
        run: |
          git commit -am "Add a changelog"
      - name: Run changelog release
        uses: cucumber/action-changelog@v1.3
        with:
          args: release --output CHANGELOG.md 1.0.0
      - name: Commit release
        run: |
          git commit -am "Release v1.0.0"
          git tag v1.0.0
      - name: Test the action
        uses: ./
        id: versions
      - name: Assert values
        run: |
          [ !"${{ steps.versions.outputs.is-release-required }}" ]

  test-tag-prefix:
    runs-on: ubuntu-latest
    name: It reads the version from a prefixed tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up git config
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
      - run: |
          touch CHANGELOG.md
      - name: Create a simple changelog file
        uses: cucumber/action-changelog@v1.3
        with:
          args: init --output CHANGELOG.md --compare-url https://example.com/abcdef...HEAD
      - name: Create an initial commit
        run: |
          git commit -am "Add a changelog"
      - name: Run changelog release
        uses: cucumber/action-changelog@v1.3
        with:
          args: release --output CHANGELOG.md 1.0.0
      - name: Commit release
        run: |
          git commit -am "Release v1.0.0"
          git tag ruby/v1.0.0
      - name: Test the action
        uses: ./
        id: versions
        with:
          tag-prefix: 'ruby/'
      - name: Assert value
        run: |
          [ "${{ steps.versions.outputs.released-version }}" == "1.0.0" ]

  test-changelog-folder:
    runs-on: ubuntu-latest
    name: It reads the version from a CHANGELOG in a folder
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up git config
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
      - run: |
          mkdir ruby
          touch ruby/CHANGELOG.md
      - name: Create a simple changelog file
        uses: cucumber/action-changelog@v1.3
        with:
          args: init --filename ruby/CHANGELOG.md --output ruby/CHANGELOG.md --compare-url https://example.com/abcdef...HEAD
      - name: Create an initial commit
        run: |
          git add .
          git commit -m "Add a changelog"
          git tag v0.0.0
      - name: Run changelog release
        uses: cucumber/action-changelog@v1.3
        with:
          args: release --filename ruby/CHANGELOG.md --output ruby/CHANGELOG.md 1.0.0
      - name: Commit release
        run: |
          git add .
          git commit -m "Release v1.0.0"
      - name: Test the action
        uses: ./
        id: versions
        with:
          changelog-directory: 'ruby'
      - name: Assert values
        run: |
          [ "${{ steps.versions.outputs.changelog-latest-version }}" == "1.0.0" ]

  test-flags-release-required-when-not-released-yet:
    runs-on: ubuntu-latest
    name: It sets is-release-required if there is no version tag and the CHANGELOG shows a version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up git config
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
      - run: touch CHANGELOG.md
      - name: Create a simple changelog file
        uses: cucumber/action-changelog@v1.3
        with:
          args: init --output CHANGELOG.md --compare-url https://example.com/abcdef...HEAD
      - name: Run changelog release
        uses: cucumber/action-changelog@v1.3
        with:
          args: release --output CHANGELOG.md 1.0.0
      - name: Commit release
        run: |
          git commit -am "Release v1.0.0"
      - name: Test the action
        uses: ./
        id: versions
      - name: Assert values
        run: |
          [ "${{ steps.versions.outputs.released-version }}" == "" ]
          [ "${{ steps.versions.outputs.changelog-latest-version }}" == "1.0.0" ]
          [ "${{ steps.versions.outputs.is-release-required }}" == "true" ]

  test-flags-release-not-required-when-not-ready-to-release:
    runs-on: ubuntu-latest
    name: It does not set is-release-required if there is no version tag and no CHANGELOG version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up git config
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
      - run: touch CHANGELOG.md
      - name: Create a simple changelog file
        uses: cucumber/action-changelog@v1.3
        with:
          args: init --output CHANGELOG.md --compare-url https://example.com/abcdef...HEAD
      - name: Commit release
        run: |
          git commit -am "Add changelog"
      - name: Test the action
        uses: ./
        id: versions
      - name: Assert values
        run: |
          [ "${{ steps.versions.outputs.released-version }}" == "" ]
          [ "${{ steps.versions.outputs.changelog-latest-version }}" == "" ]
          [ "${{ steps.versions.outputs.is-release-required }}" == "" ]